from enum import Enum


class MarketType(str, Enum):
    KOSPI = "KOSPI"
    KOSDAQ = "KOSDAQ"
    ETF = "ETF"
    ETN = "ETN"
    OTHER = "OTHER"


class PriceLevelType(str, Enum):
    SUPPORT = "SUPPORT"
    RESISTANCE = "RESISTANCE"


class SupportStatus(str, Enum):
    WAITING = "WAITING"
    TESTING_SUPPORT = "TESTING_SUPPORT"
    DIRECT_REBOUND_SUCCESS = "DIRECT_REBOUND_SUCCESS"
    BREAK_REBOUND_SUCCESS = "BREAK_REBOUND_SUCCESS"
    REUSABLE = "REUSABLE"
    INVALID = "INVALID"


class SignalType(str, Enum):
    SUPPORT_NEAR = "SUPPORT_NEAR"
    SUPPORT_TESTING = "SUPPORT_TESTING"
    SUPPORT_DIRECT_REBOUND_SUCCESS = "SUPPORT_DIRECT_REBOUND_SUCCESS"
    SUPPORT_BREAK_REBOUND_SUCCESS = "SUPPORT_BREAK_REBOUND_SUCCESS"
    SUPPORT_REUSABLE = "SUPPORT_REUSABLE"
    SUPPORT_INVALIDATED = "SUPPORT_INVALIDATED"
    RESISTANCE_NEAR = "RESISTANCE_NEAR"
    RESISTANCE_BREAKOUT = "RESISTANCE_BREAKOUT"
    RESISTANCE_REJECTED = "RESISTANCE_REJECTED"


class ThemeRoleType(str, Enum):
    LEADER = "LEADER"
    FOLLOWER = "FOLLOWER"


class ContentCategory(str, Enum):
    STOCK_ANALYSIS = "STOCK_ANALYSIS"
    THEME_BRIEF = "THEME_BRIEF"
    MARKET_SUMMARY = "MARKET_SUMMARY"
    SHORTS = "SHORTS"
    NOTICE = "NOTICE"
